# Generated by Django 5.0.2 on 2024-02-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvPointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi_id', models.IntegerField()),
                ('poi_name', models.CharField(max_length=100)),
                ('poi_latitude', models.FloatField()),
                ('poi_longitude', models.FloatField()),
                ('poi_category', models.CharField(max_length=50)),
                ('poi_ratings', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='JsonPointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi_id', models.IntegerField()),
                ('poi_name', models.CharField(max_length=100)),
                ('poi_latitude', models.FloatField()),
                ('poi_longitude', models.FloatField()),
                ('poi_category', models.CharField(max_length=50)),
                ('poi_ratings', models.FloatField()),
                ('poi_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='XmlPointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi_id', models.IntegerField()),
                ('poi_name', models.CharField(max_length=100)),
                ('poi_latitude', models.FloatField()),
                ('poi_longitude', models.FloatField()),
                ('poi_category', models.CharField(max_length=50)),
                ('poi_ratings', models.FloatField()),
            ],
        ),
    ]
