# Generated by Django 5.0.2 on 2024-02-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoDataImportApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvpointofinterest',
            name='id',
        ),
        migrations.RemoveField(
            model_name='jsonpointofinterest',
            name='id',
        ),
        migrations.RemoveField(
            model_name='xmlpointofinterest',
            name='id',
        ),
        migrations.AlterField(
            model_name='csvpointofinterest',
            name='poi_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='csvpointofinterest',
            name='poi_ratings',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jsonpointofinterest',
            name='poi_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='jsonpointofinterest',
            name='poi_ratings',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='xmlpointofinterest',
            name='poi_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='xmlpointofinterest',
            name='poi_ratings',
            field=models.TextField(),
        ),
    ]
