# Generated by Django 5.0.2 on 2024-02-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoDataImportApp', '0002_remove_csvpointofinterest_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsOfInterest',
            fields=[
                ('poi_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('poi_name', models.CharField(max_length=100)),
                ('poi_latitude', models.FloatField()),
                ('poi_longitude', models.FloatField()),
                ('poi_category', models.CharField(max_length=50)),
                ('poi_ratings', models.TextField()),
                ('poi_description', models.TextField()),
                ('data_origin', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='CsvPointOfInterest',
        ),
        migrations.DeleteModel(
            name='JsonPointOfInterest',
        ),
        migrations.DeleteModel(
            name='XmlPointOfInterest',
        ),
    ]
