# Generated by Django 5.0.2 on 2024-02-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoDataImportApp', '0003_pointsofinterest_delete_csvpointofinterest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsofinterest',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
